In [1]:
from nba_api.stats.endpoints import leaguedashplayerstats
# import json
import pandas as pd

In [5]:
lsm_json = leaguedashplayerstats.LeagueDashPlayerStats(
    last_n_games = '0',
    measure_type_detailed_defense = 'Advanced',
    month = '0',
    opponent_team_id = '0',
    po_round_nullable = '0',
    pace_adjust = 'N',
    per_mode_detailed = 'PerGame',
    period = '0',
    league_id_nullable = '00', 
    season_type_all_star = 'Regular Season',
    team_id_nullable = '0',
    two_way_nullable = '0',
    season = '2019-20')

In [6]:
lsm_json

In [10]:
lsm_json = lsm_json.get_normalized_dict()

In [14]:
lsm_json = lsm_json['LeagueDashPlayerStats']

In [15]:
df = pd.DataFrame(lsm_json)

In [17]:
df.head()

,AGE,AST_PCT,AST_PCT_RANK,AST_RATIO,AST_RATIO_RANK,AST_TO,AST_TO_RANK,CFID,CFPARAMS,DEF_RATING,...,W_PCT_RANK,W_RANK,sp_work_DEF_RATING,sp_work_DEF_RATING_RANK,sp_work_NET_RATING,sp_work_NET_RATING_RANK,sp_work_OFF_RATING,sp_work_OFF_RATING_RANK,sp_work_PACE,sp_work_PACE_RANK
0,24.0,0.165,147,19.1,157,2.28,104,5,"203932,1610612753",109.7,...,247,152,109.7,334,-1.2,273,108.6,237,99.72,451
1,23.0,0.188,116,24.6,79,2.56,66,5,"1628988,1610612754",106.9,...,103,51,106.9,203,2.2,175,109.1,215,100.31,416
2,26.0,0.068,423,10.3,441,0.88,441,5,"1627846,1610612760",105.2,...,77,91,105.2,145,-4.2,359,100.9,451,101.79,317
3,21.0,0.043,502,11.4,401,2.00,152,5,"1629690,1610612741",104.4,...,473,462,104.4,114,17.1,18,121.4,12,100.37,413
4,23.0,0.057,461,12.4,374,2.14,132,5,"1629678,1610612764",110.0,...,473,386,110.0,343,-7.1,423,102.9,411,103.13,225

In [19]:
df.to_csv("GreatData.csv")

In [20]:
mane = list(df.columns)

In [21]:
mane

['AGE',
 'AST_PCT',
 'AST_PCT_RANK',
 'AST_RATIO',
 'AST_RATIO_RANK',
 'AST_TO',
 'AST_TO_RANK',
 'CFID',
 'CFPARAMS',
 'DEF_RATING',
 'DEF_RATING_RANK',
 'DREB_PCT',
 'DREB_PCT_RANK',
 'EFG_PCT',
 'EFG_PCT_RANK',
 'E_DEF_RATING',
 'E_DEF_RATING_RANK',
 'E_NET_RATING',
 'E_NET_RATING_RANK',
 'E_OFF_RATING',
 'E_OFF_RATING_RANK',
 'E_PACE',
 'E_PACE_RANK',
 'E_TOV_PCT',
 'E_TOV_PCT_RANK',
 'E_USG_PCT',
 'E_USG_PCT_RANK',
 'FGA',
 'FGA_PG',
 'FGA_PG_RANK',
 'FGA_RANK',
 'FGM',
 'FGM_PG',
 'FGM_PG_RANK',
 'FGM_RANK',
 'FG_PCT',
 'FG_PCT_RANK',
 'GP',
 'GP_RANK',
 'L',
 'L_RANK',
 'MIN',
 'MIN_RANK',
 'NET_RATING',
 'NET_RATING_RANK',
 'OFF_RATING',
 'OFF_RATING_RANK',
 'OREB_PCT',
 'OREB_PCT_RANK',
 'PACE',
 'PACE_PER40',
 'PACE_RANK',
 'PIE',
 'PIE_RANK',
 'PLAYER_ID',
 'PLAYER_NAME',
 'POSS',
 'REB_PCT',
 'REB_PCT_RANK',
 'TEAM_ABBREVIATION',
 'TEAM_ID',
 'TM_TOV_PCT',
 'TM_TOV_PCT_RANK',
 'TS_PCT',
 'TS_PCT_RANK',
 'USG_PCT',
 'USG_PCT_RANK',
 'W',
 'W_PCT',
 'W_PCT_RANK',
 'W_RANK',
 'sp_work_DEF_RATING',
 'sp_work_DEF_RATING_RANK',
 'sp_work_NET_RATING',
 'sp_work_NET_RATING_RANK',
 'sp_work_OFF_RATING',
 'sp_work_OFF_RATING_RANK',
 'sp_work_PACE',
 'sp_work_PACE_RANK']